name: Docker Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: https://gitea.com/actions/checkout@v4

      - name: Docker login
        run: echo "${{ secrets.REGISTRY_TOKEN }}" | docker login https://gitea.mythsman.com -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

      - name: Docker build and push
        run: |
          docker buildx build \
            --file Dockerfile \
            --tag gitea.mythsman.com/${{ secrets.REGISTRY_USERNAME }}/mouban:latest \
            --push \
            .
