name: Go Build

on:
  workflow_dispatch:  # 支持手动触发

jobs:
  build:
    env:
      RUNNER_TOOL_CACHE: /toolcache  # 指定缓存目录

    runs-on: ubuntu-latest
    
    env:
      GOPROXY: https://goproxy.cn,direct  # 使用国内代理加速依赖下载
      GO111MODULE: on
    
    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: https://gitea.com/actions/checkout@v4

      - name: Set up Go
        uses: https://gitea.com/actions/setup-go@v5
        with:
          go-version: '1.26'

      - name: Show Go version
        run: go version

      - name: Build
        run: ./build.sh

      - name: Show
        run: ls -alh 

